[2024-05-12T16:23:53.700+0000] {processor.py:153} INFO - Started process (PID=81) to work on /opt/airflow/dags/main.py
[2024-05-12T16:23:53.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:23:53.718+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:23:53.718+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:23:54.082+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:23:54.044+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:23:54.101+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:23:54.433+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.824 seconds
[2024-05-12T16:25:19.089+0000] {processor.py:153} INFO - Started process (PID=165) to work on /opt/airflow/dags/main.py
[2024-05-12T16:25:19.253+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:25:19.438+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:25:19.438+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:25:19.795+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:25:19.793+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:25:19.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:25:19.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.923 seconds
[2024-05-12T16:25:50.209+0000] {processor.py:153} INFO - Started process (PID=225) to work on /opt/airflow/dags/main.py
[2024-05-12T16:25:50.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:25:50.220+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:25:50.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:25:50.277+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:25:50.270+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:25:50.281+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:25:50.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.196 seconds
[2024-05-12T16:26:20.598+0000] {processor.py:153} INFO - Started process (PID=280) to work on /opt/airflow/dags/main.py
[2024-05-12T16:26:20.602+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:26:20.605+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:26:20.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:26:20.642+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:26:20.640+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:26:20.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:26:20.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.104 seconds
[2024-05-12T16:26:50.866+0000] {processor.py:153} INFO - Started process (PID=341) to work on /opt/airflow/dags/main.py
[2024-05-12T16:26:50.869+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:26:50.872+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:26:50.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:26:50.925+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:26:50.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:26:50.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:26:50.981+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.129 seconds
[2024-05-12T16:27:21.168+0000] {processor.py:153} INFO - Started process (PID=401) to work on /opt/airflow/dags/main.py
[2024-05-12T16:27:21.181+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:27:21.183+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:27:21.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:27:22.106+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:27:22.101+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:27:22.114+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:27:22.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.089 seconds
[2024-05-12T16:27:52.674+0000] {processor.py:153} INFO - Started process (PID=456) to work on /opt/airflow/dags/main.py
[2024-05-12T16:27:52.676+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:27:52.679+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:27:52.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:27:52.738+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:27:52.735+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:27:52.739+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:27:52.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.239 seconds
[2024-05-12T16:28:23.492+0000] {processor.py:153} INFO - Started process (PID=516) to work on /opt/airflow/dags/main.py
[2024-05-12T16:28:23.496+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:28:23.504+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:28:23.504+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:28:23.615+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:28:23.613+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:28:23.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:28:23.801+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.326 seconds
[2024-05-12T16:28:54.144+0000] {processor.py:153} INFO - Started process (PID=571) to work on /opt/airflow/dags/main.py
[2024-05-12T16:28:54.146+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:28:54.148+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:28:54.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:28:54.215+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:28:54.212+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:28:54.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:28:54.273+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.139 seconds
[2024-05-12T16:29:26.211+0000] {processor.py:153} INFO - Started process (PID=632) to work on /opt/airflow/dags/main.py
[2024-05-12T16:29:26.219+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:29:26.221+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:29:26.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:29:26.332+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:29:26.330+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:29:26.334+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:29:26.598+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.464 seconds
[2024-05-12T16:29:57.082+0000] {processor.py:153} INFO - Started process (PID=686) to work on /opt/airflow/dags/main.py
[2024-05-12T16:29:57.085+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:29:57.087+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:29:57.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:29:57.125+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:29:57.123+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:29:57.127+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:29:57.194+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.126 seconds
[2024-05-12T16:30:28.230+0000] {processor.py:153} INFO - Started process (PID=747) to work on /opt/airflow/dags/main.py
[2024-05-12T16:30:28.233+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:30:28.248+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:30:28.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:30:28.949+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:30:28.947+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:30:28.996+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:30:29.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.091 seconds
[2024-05-12T16:30:59.576+0000] {processor.py:153} INFO - Started process (PID=796) to work on /opt/airflow/dags/main.py
[2024-05-12T16:30:59.579+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:30:59.603+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:30:59.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:30:59.702+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:30:59.698+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:30:59.723+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:31:00.293+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.739 seconds
[2024-05-12T16:31:31.490+0000] {processor.py:153} INFO - Started process (PID=858) to work on /opt/airflow/dags/main.py
[2024-05-12T16:31:31.493+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:31:31.498+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:31:31.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:31:31.538+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:31:31.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:31:31.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:31:31.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.117 seconds
[2024-05-12T16:32:01.884+0000] {processor.py:153} INFO - Started process (PID=919) to work on /opt/airflow/dags/main.py
[2024-05-12T16:32:01.885+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:32:01.888+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:32:01.888+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:32:01.966+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:32:01.964+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:32:01.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:32:02.141+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.272 seconds
[2024-05-12T16:32:32.861+0000] {processor.py:153} INFO - Started process (PID=975) to work on /opt/airflow/dags/main.py
[2024-05-12T16:32:32.863+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:32:32.866+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:32:32.866+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:32:32.905+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:32:32.903+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:32:32.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:32:32.963+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.121 seconds
[2024-05-12T16:33:03.396+0000] {processor.py:153} INFO - Started process (PID=1033) to work on /opt/airflow/dags/main.py
[2024-05-12T16:33:03.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:33:03.407+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:33:03.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:33:03.461+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:33:03.459+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:33:03.465+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:33:03.568+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.193 seconds
[2024-05-12T16:33:33.960+0000] {processor.py:153} INFO - Started process (PID=1089) to work on /opt/airflow/dags/main.py
[2024-05-12T16:33:33.961+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:33:33.966+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:33:33.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:33:34.031+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:33:34.029+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:33:34.033+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:33:34.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.168 seconds
[2024-05-12T16:34:04.474+0000] {processor.py:153} INFO - Started process (PID=1153) to work on /opt/airflow/dags/main.py
[2024-05-12T16:34:04.476+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:34:04.478+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:34:04.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:34:04.568+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:34:04.566+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:34:04.570+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:34:04.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.228 seconds
[2024-05-12T16:34:36.773+0000] {processor.py:153} INFO - Started process (PID=1210) to work on /opt/airflow/dags/main.py
[2024-05-12T16:34:36.777+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:34:36.792+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:34:36.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:34:37.347+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:34:37.344+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:34:37.376+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:34:37.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.861 seconds
[2024-05-12T16:35:10.834+0000] {processor.py:153} INFO - Started process (PID=1263) to work on /opt/airflow/dags/main.py
[2024-05-12T16:35:10.846+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:35:10.848+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:35:10.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:35:11.032+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:35:11.030+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:35:11.038+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:35:11.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.621 seconds
[2024-05-12T16:35:43.353+0000] {processor.py:153} INFO - Started process (PID=1321) to work on /opt/airflow/dags/main.py
[2024-05-12T16:35:43.356+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:35:43.402+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:35:43.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:35:43.770+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:35:43.768+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:35:43.800+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:35:44.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.965 seconds
[2024-05-12T16:36:14.645+0000] {processor.py:153} INFO - Started process (PID=1375) to work on /opt/airflow/dags/main.py
[2024-05-12T16:36:14.659+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:36:14.665+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:36:14.665+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:36:14.758+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:36:14.750+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:36:14.771+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:36:14.912+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.284 seconds
[2024-05-12T16:36:45.729+0000] {processor.py:153} INFO - Started process (PID=1436) to work on /opt/airflow/dags/main.py
[2024-05-12T16:36:45.734+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:36:45.737+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:36:45.737+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:36:45.790+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:36:45.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:36:45.793+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:36:45.937+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.222 seconds
[2024-05-12T16:37:16.539+0000] {processor.py:153} INFO - Started process (PID=1491) to work on /opt/airflow/dags/main.py
[2024-05-12T16:37:16.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:37:16.555+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:37:16.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:37:16.836+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:37:16.834+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:37:16.838+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:37:17.043+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.537 seconds
[2024-05-12T16:38:09.079+0000] {processor.py:153} INFO - Started process (PID=1559) to work on /opt/airflow/dags/main.py
[2024-05-12T16:38:09.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:38:09.121+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:38:09.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:38:09.321+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:38:09.316+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:38:09.340+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:38:09.588+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.550 seconds
[2024-05-12T16:38:40.634+0000] {processor.py:153} INFO - Started process (PID=1614) to work on /opt/airflow/dags/main.py
[2024-05-12T16:38:40.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:38:40.638+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:38:40.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:38:40.687+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:38:40.685+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:38:40.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:38:40.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.142 seconds
[2024-05-12T16:39:10.988+0000] {processor.py:153} INFO - Started process (PID=1677) to work on /opt/airflow/dags/main.py
[2024-05-12T16:39:10.990+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:39:10.995+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:39:10.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:39:11.138+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:39:11.136+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:39:11.140+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:39:11.262+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.289 seconds
[2024-05-12T16:39:41.703+0000] {processor.py:153} INFO - Started process (PID=1740) to work on /opt/airflow/dags/main.py
[2024-05-12T16:39:41.704+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:39:41.706+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:39:41.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:39:41.741+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:39:41.739+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:39:41.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:39:41.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.121 seconds
[2024-05-12T16:40:12.128+0000] {processor.py:153} INFO - Started process (PID=1792) to work on /opt/airflow/dags/main.py
[2024-05-12T16:40:12.130+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:40:12.134+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:40:12.132+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:40:12.182+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:40:12.172+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:40:12.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:40:12.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.159 seconds
[2024-05-12T16:40:42.876+0000] {processor.py:153} INFO - Started process (PID=1855) to work on /opt/airflow/dags/main.py
[2024-05-12T16:40:42.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:40:42.894+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:40:42.893+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:40:42.944+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:40:42.941+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:40:42.945+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:40:43.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.178 seconds
[2024-05-12T16:41:13.563+0000] {processor.py:153} INFO - Started process (PID=1914) to work on /opt/airflow/dags/main.py
[2024-05-12T16:41:13.565+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:41:13.581+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:41:13.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:41:13.626+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:41:13.623+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:41:13.637+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:41:13.740+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.212 seconds
[2024-05-12T16:41:44.147+0000] {processor.py:153} INFO - Started process (PID=1971) to work on /opt/airflow/dags/main.py
[2024-05-12T16:41:44.148+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:41:44.151+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:41:44.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:41:44.197+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:41:44.194+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:41:44.198+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:41:44.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.106 seconds
[2024-05-12T16:42:14.491+0000] {processor.py:153} INFO - Started process (PID=2029) to work on /opt/airflow/dags/main.py
[2024-05-12T16:42:14.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:42:14.499+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:42:14.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:42:14.589+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:42:14.584+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:42:14.590+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:42:14.685+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.212 seconds
[2024-05-12T16:42:45.472+0000] {processor.py:153} INFO - Started process (PID=2084) to work on /opt/airflow/dags/main.py
[2024-05-12T16:42:45.473+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:42:45.476+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:42:45.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:42:45.515+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:42:45.513+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:42:45.517+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:42:45.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.116 seconds
[2024-05-12T16:43:15.869+0000] {processor.py:153} INFO - Started process (PID=2149) to work on /opt/airflow/dags/main.py
[2024-05-12T16:43:15.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:43:15.886+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:43:15.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:43:16.034+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:43:16.025+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:43:16.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:43:16.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.309 seconds
[2024-05-12T16:43:46.587+0000] {processor.py:153} INFO - Started process (PID=2199) to work on /opt/airflow/dags/main.py
[2024-05-12T16:43:46.588+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:43:46.591+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:43:46.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:43:46.689+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:43:46.686+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:43:46.699+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:43:46.786+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.208 seconds
[2024-05-12T16:44:17.387+0000] {processor.py:153} INFO - Started process (PID=2262) to work on /opt/airflow/dags/main.py
[2024-05-12T16:44:17.404+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:44:17.418+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:44:17.418+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:44:17.597+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:44:17.595+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:44:17.602+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:44:17.703+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.331 seconds
[2024-05-12T16:44:48.476+0000] {processor.py:153} INFO - Started process (PID=2314) to work on /opt/airflow/dags/main.py
[2024-05-12T16:44:48.481+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:44:48.485+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:44:48.484+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:44:48.579+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:44:48.577+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:44:48.581+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:44:48.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.205 seconds
[2024-05-12T16:45:18.961+0000] {processor.py:153} INFO - Started process (PID=2377) to work on /opt/airflow/dags/main.py
[2024-05-12T16:45:18.963+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:45:18.973+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:45:18.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:45:19.070+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:45:19.068+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:45:19.071+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:45:19.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.204 seconds
[2024-05-12T16:45:49.925+0000] {processor.py:153} INFO - Started process (PID=2436) to work on /opt/airflow/dags/main.py
[2024-05-12T16:45:49.931+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:45:49.936+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:45:49.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:45:50.015+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:45:50.013+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:45:50.017+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:45:50.147+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.241 seconds
[2024-05-12T16:46:20.401+0000] {processor.py:153} INFO - Started process (PID=2493) to work on /opt/airflow/dags/main.py
[2024-05-12T16:46:20.403+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:46:20.406+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:46:20.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:46:20.491+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:46:20.459+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:46:20.495+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:46:20.750+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.381 seconds
[2024-05-12T16:46:55.775+0000] {processor.py:153} INFO - Started process (PID=2551) to work on /opt/airflow/dags/main.py
[2024-05-12T16:46:55.844+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:46:55.861+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:46:55.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:46:56.568+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:46:56.565+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:46:56.582+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:46:56.823+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.097 seconds
[2024-05-12T16:47:27.101+0000] {processor.py:153} INFO - Started process (PID=2605) to work on /opt/airflow/dags/main.py
[2024-05-12T16:47:27.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:47:27.110+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:47:27.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:47:27.230+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:47:27.226+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:47:27.232+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:47:27.316+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.225 seconds
[2024-05-12T16:47:57.922+0000] {processor.py:153} INFO - Started process (PID=2669) to work on /opt/airflow/dags/main.py
[2024-05-12T16:47:57.940+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:47:57.954+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:47:57.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:47:58.019+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:47:58.006+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:47:58.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:47:58.129+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.244 seconds
[2024-05-12T16:48:30.617+0000] {processor.py:153} INFO - Started process (PID=2727) to work on /opt/airflow/dags/main.py
[2024-05-12T16:48:30.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:48:30.679+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:48:30.678+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:48:31.631+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:48:31.628+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:48:31.635+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:48:31.875+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.291 seconds
[2024-05-12T16:49:18.713+0000] {processor.py:153} INFO - Started process (PID=2783) to work on /opt/airflow/dags/main.py
[2024-05-12T16:49:18.726+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:49:18.755+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:49:18.754+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:49:19.029+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:49:19.026+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:49:19.041+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:49:19.175+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.494 seconds
[2024-05-12T16:50:18.433+0000] {processor.py:153} INFO - Started process (PID=2854) to work on /opt/airflow/dags/main.py
[2024-05-12T16:50:18.450+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:50:18.467+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:50:18.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:50:19.529+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:50:19.527+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:50:19.533+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:50:19.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.534 seconds
[2024-05-12T16:50:53.878+0000] {processor.py:153} INFO - Started process (PID=2893) to work on /opt/airflow/dags/main.py
[2024-05-12T16:50:53.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:50:53.883+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:50:53.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:50:54.166+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:50:54.157+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:50:54.183+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:50:54.777+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.949 seconds
[2024-05-12T16:51:26.471+0000] {processor.py:153} INFO - Started process (PID=2930) to work on /opt/airflow/dags/main.py
[2024-05-12T16:51:26.504+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:51:26.525+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:51:26.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:51:27.924+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:51:27.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:51:28.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:51:28.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.249 seconds
[2024-05-12T16:52:28.544+0000] {processor.py:153} INFO - Started process (PID=3005) to work on /opt/airflow/dags/main.py
[2024-05-12T16:52:28.641+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:52:28.691+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:52:28.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:52:30.541+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:52:30.535+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:52:30.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:52:30.916+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.436 seconds
[2024-05-12T16:53:09.730+0000] {processor.py:153} INFO - Started process (PID=3048) to work on /opt/airflow/dags/main.py
[2024-05-12T16:53:09.876+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:53:09.925+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:53:09.924+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:53:12.068+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:53:12.066+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:53:12.098+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:53:12.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 3.267 seconds
[2024-05-12T16:53:53.240+0000] {processor.py:153} INFO - Started process (PID=3095) to work on /opt/airflow/dags/main.py
[2024-05-12T16:53:53.248+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:53:53.254+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:53:53.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:53:53.371+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:53:53.345+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:53:53.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:53:54.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.943 seconds
[2024-05-12T16:54:35.622+0000] {processor.py:153} INFO - Started process (PID=3140) to work on /opt/airflow/dags/main.py
[2024-05-12T16:54:35.692+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:54:35.710+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:54:35.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:54:36.833+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:54:36.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:54:36.863+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:54:37.359+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.749 seconds
[2024-05-12T16:55:30.400+0000] {processor.py:153} INFO - Started process (PID=3194) to work on /opt/airflow/dags/main.py
[2024-05-12T16:55:30.430+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:55:30.474+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:55:30.474+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:55:31.777+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:55:31.742+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:55:31.780+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:55:32.697+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.616 seconds
[2024-05-12T16:57:50.747+0000] {processor.py:153} INFO - Started process (PID=3286) to work on /opt/airflow/dags/main.py
[2024-05-12T16:57:50.840+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T16:57:51.772+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:57:51.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T16:58:01.357+0000] {logging_mixin.py:137} INFO - [2024-05-12T16:58:00.823+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 60
    with open('C:\Users\Usman Babar\Desktop\Mlops_Assignment02\data\extracted_data.csv', 'w', newline='', encoding='utf-8') as csvfile:
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[2024-05-12T16:58:01.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T16:58:05.760+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 15.218 seconds
[2024-05-12T17:13:01.457+0000] {processor.py:153} INFO - Started process (PID=77) to work on /opt/airflow/dags/main.py
[2024-05-12T17:13:01.474+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:13:01.523+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:13:01.480+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:13:02.236+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:13:02.232+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:13:02.269+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:13:02.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.437 seconds
[2024-05-12T17:14:13.405+0000] {processor.py:153} INFO - Started process (PID=155) to work on /opt/airflow/dags/main.py
[2024-05-12T17:14:13.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:14:13.457+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:14:13.456+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:14:13.831+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:14:13.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:14:13.889+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:14:14.386+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.021 seconds
[2024-05-12T17:15:07.222+0000] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/main.py
[2024-05-12T17:15:07.229+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:15:07.238+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:15:07.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:15:07.318+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:15:07.313+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:15:07.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:15:07.527+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.340 seconds
[2024-05-12T17:15:38.460+0000] {processor.py:153} INFO - Started process (PID=284) to work on /opt/airflow/dags/main.py
[2024-05-12T17:15:38.462+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:15:38.466+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:15:38.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:15:38.560+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:15:38.557+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:15:38.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:15:38.811+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.408 seconds
[2024-05-12T17:16:09.018+0000] {processor.py:153} INFO - Started process (PID=338) to work on /opt/airflow/dags/main.py
[2024-05-12T17:16:09.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:16:09.040+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:16:09.040+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:16:09.175+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:16:09.172+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:16:09.177+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:16:09.272+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.277 seconds
[2024-05-12T17:16:42.560+0000] {processor.py:153} INFO - Started process (PID=393) to work on /opt/airflow/dags/main.py
[2024-05-12T17:16:42.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:16:42.599+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:16:42.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:16:42.890+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:16:42.884+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:16:42.913+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:16:43.404+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.895 seconds
[2024-05-12T17:17:27.412+0000] {processor.py:153} INFO - Started process (PID=440) to work on /opt/airflow/dags/main.py
[2024-05-12T17:17:27.428+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:17:27.462+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:17:27.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:17:27.604+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:17:27.602+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:17:27.618+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:17:28.466+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.079 seconds
[2024-05-12T17:23:09.803+0000] {processor.py:153} INFO - Started process (PID=101) to work on /opt/airflow/dags/main.py
[2024-05-12T17:23:09.857+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:23:09.864+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:23:09.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:23:09.997+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:23:09.994+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:23:10.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:23:10.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.617 seconds
[2024-05-12T17:24:24.462+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/main.py
[2024-05-12T17:24:24.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:24:24.499+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:24:24.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:24:25.060+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:24:25.058+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/main.py", line 128
    os.system('git add C:\Users\Usman Babar\Desktop\Mlops_Assignment02\.dvc/')
             ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 10-11: truncated \UXXXXXXXX escape
[2024-05-12T17:24:25.118+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:24:25.533+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.263 seconds
[2024-05-12T17:27:29.957+0000] {processor.py:153} INFO - Started process (PID=69) to work on /opt/airflow/dags/main.py
[2024-05-12T17:27:29.999+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:27:30.015+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:30.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:27:32.742+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:27:33.847+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:33.846+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:mlops_A2_dag
[2024-05-12T17:27:33.931+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:33.930+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:mlops_A2_dag
[2024-05-12T17:27:33.977+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:33.976+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:mlops_A2_dag
[2024-05-12T17:27:33.979+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:33.978+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:27:34.040+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:34.038+0000] {dag.py:2711} INFO - Creating ORM DAG for mlops_A2_dag
[2024-05-12T17:27:34.111+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:27:34.110+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-11T17:27:34.109181+00:00, run_after=2024-05-12T17:27:34.109181+00:00
[2024-05-12T17:27:34.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 4.327 seconds
[2024-05-12T17:28:15.084+0000] {processor.py:153} INFO - Started process (PID=130) to work on /opt/airflow/dags/main.py
[2024-05-12T17:28:15.101+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:28:15.117+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:28:15.116+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:28:18.975+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:28:19.407+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:28:19.377+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:28:20.162+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:28:20.149+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:28:21.175+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 6.241 seconds
[2024-05-12T17:29:29.722+0000] {processor.py:153} INFO - Started process (PID=214) to work on /opt/airflow/dags/main.py
[2024-05-12T17:29:29.740+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:29:29.742+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:29:29.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:29:32.468+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:29:32.861+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:29:32.858+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:29:33.348+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:29:33.348+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:29:33.625+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 4.003 seconds
[2024-05-12T17:30:05.782+0000] {processor.py:153} INFO - Started process (PID=268) to work on /opt/airflow/dags/main.py
[2024-05-12T17:30:05.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:30:05.847+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:30:05.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:30:07.726+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:30:07.994+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:30:07.992+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:30:08.255+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:30:08.252+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:30:08.492+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.761 seconds
[2024-05-12T17:30:42.129+0000] {processor.py:153} INFO - Started process (PID=322) to work on /opt/airflow/dags/main.py
[2024-05-12T17:30:42.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:30:42.144+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:30:42.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:30:43.855+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:30:44.174+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:30:44.173+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:30:44.637+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:30:44.611+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:30:45.048+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.942 seconds
[2024-05-12T17:31:15.352+0000] {processor.py:153} INFO - Started process (PID=387) to work on /opt/airflow/dags/main.py
[2024-05-12T17:31:15.354+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:31:15.356+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:31:15.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:31:15.767+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:31:15.852+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:31:15.851+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:31:15.937+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:31:15.936+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:31:16.001+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.659 seconds
[2024-05-12T17:31:46.426+0000] {processor.py:153} INFO - Started process (PID=447) to work on /opt/airflow/dags/main.py
[2024-05-12T17:31:46.455+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:31:46.458+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:31:46.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:31:47.534+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:31:47.635+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:31:47.633+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:31:47.747+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:31:47.747+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:31:47.880+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.493 seconds
[2024-05-12T17:32:21.660+0000] {processor.py:153} INFO - Started process (PID=500) to work on /opt/airflow/dags/main.py
[2024-05-12T17:32:21.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:32:21.685+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:32:21.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:32:22.980+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:32:23.369+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:32:23.368+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:32:23.679+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:32:23.678+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:32:23.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.321 seconds
[2024-05-12T17:32:59.107+0000] {processor.py:153} INFO - Started process (PID=563) to work on /opt/airflow/dags/main.py
[2024-05-12T17:32:59.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:32:59.129+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:32:59.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:33:00.741+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:33:00.949+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:33:00.946+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:33:01.166+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:33:01.165+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:33:01.459+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.401 seconds
[2024-05-12T17:33:40.163+0000] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/main.py
[2024-05-12T17:33:40.185+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:33:40.203+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:33:40.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:33:41.591+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:33:41.954+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:33:41.953+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:33:42.327+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:33:42.327+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:33:42.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.530 seconds
[2024-05-12T17:34:29.403+0000] {processor.py:153} INFO - Started process (PID=684) to work on /opt/airflow/dags/main.py
[2024-05-12T17:34:29.407+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:34:29.444+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:34:29.444+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:34:31.864+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:34:32.607+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:34:32.578+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:34:33.200+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:34:33.200+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:34:33.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 4.587 seconds
[2024-05-12T17:35:11.077+0000] {processor.py:153} INFO - Started process (PID=738) to work on /opt/airflow/dags/main.py
[2024-05-12T17:35:11.093+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:35:11.114+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:35:11.113+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:35:13.795+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:35:14.284+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:35:14.283+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:35:15.270+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:35:15.265+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:35:15.952+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 4.926 seconds
[2024-05-12T17:35:55.484+0000] {processor.py:153} INFO - Started process (PID=804) to work on /opt/airflow/dags/main.py
[2024-05-12T17:35:55.500+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:35:55.522+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:35:55.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:35:58.064+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:35:58.390+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:35:58.356+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:35:59.024+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:35:59.023+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:35:59.344+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 3.932 seconds
[2024-05-12T17:36:46.574+0000] {processor.py:153} INFO - Started process (PID=871) to work on /opt/airflow/dags/main.py
[2024-05-12T17:36:46.590+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:36:46.607+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:36:46.606+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:36:49.233+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:36:49.714+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:36:49.713+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:36:50.412+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:36:50.411+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:36:50.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 4.279 seconds
[2024-05-12T17:38:05.739+0000] {processor.py:153} INFO - Started process (PID=953) to work on /opt/airflow/dags/main.py
[2024-05-12T17:38:05.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:38:05.776+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:38:05.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:38:10.254+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:38:11.038+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:38:11.036+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:38:11.868+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:38:11.865+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:38:12.215+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 6.590 seconds
[2024-05-12T17:38:46.902+0000] {processor.py:153} INFO - Started process (PID=1007) to work on /opt/airflow/dags/main.py
[2024-05-12T17:38:46.912+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:38:46.922+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:38:46.921+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:38:50.370+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:38:51.072+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:38:51.059+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:38:51.748+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:38:51.747+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:38:52.124+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 5.290 seconds
[2024-05-12T17:40:06.898+0000] {processor.py:153} INFO - Started process (PID=1091) to work on /opt/airflow/dags/main.py
[2024-05-12T17:40:06.900+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:40:06.913+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:40:06.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:40:09.373+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:40:09.548+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:40:09.547+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:40:09.790+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:40:09.790+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:40:10.144+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 3.310 seconds
[2024-05-12T17:40:43.174+0000] {processor.py:153} INFO - Started process (PID=1152) to work on /opt/airflow/dags/main.py
[2024-05-12T17:40:43.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:40:43.200+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:40:43.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:40:44.869+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:40:45.136+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:40:45.122+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:40:45.464+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:40:45.464+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:40:45.660+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.523 seconds
[2024-05-12T17:41:24.535+0000] {processor.py:153} INFO - Started process (PID=1207) to work on /opt/airflow/dags/main.py
[2024-05-12T17:41:24.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:41:24.579+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:41:24.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:41:28.011+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:41:28.385+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:41:28.384+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:41:28.964+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:41:28.964+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:41:30.165+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 5.884 seconds
[2024-05-12T17:42:21.445+0000] {processor.py:153} INFO - Started process (PID=1268) to work on /opt/airflow/dags/main.py
[2024-05-12T17:42:21.459+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:42:21.475+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:42:21.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:42:24.559+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:42:25.097+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:42:25.094+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:42:25.753+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:42:25.752+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:42:26.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 5.017 seconds
[2024-05-12T17:43:03.678+0000] {processor.py:153} INFO - Started process (PID=1313) to work on /opt/airflow/dags/main.py
[2024-05-12T17:43:03.695+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:43:03.699+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:43:03.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:43:05.058+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:43:05.256+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:43:05.253+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:43:05.520+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:43:05.519+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:43:05.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.088 seconds
[2024-05-12T17:43:52.565+0000] {processor.py:153} INFO - Started process (PID=1362) to work on /opt/airflow/dags/main.py
[2024-05-12T17:43:52.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:43:52.597+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:43:52.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:43:55.896+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:43:56.656+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:43:56.655+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:43:57.372+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:43:57.371+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:43:58.067+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 5.577 seconds
[2024-05-12T17:44:41.795+0000] {processor.py:153} INFO - Started process (PID=1420) to work on /opt/airflow/dags/main.py
[2024-05-12T17:44:41.809+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:44:41.831+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:44:41.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:44:45.376+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:44:45.830+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:44:45.809+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:44:46.503+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:44:46.490+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:44:46.869+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 5.192 seconds
[2024-05-12T17:45:46.088+0000] {processor.py:153} INFO - Started process (PID=1499) to work on /opt/airflow/dags/main.py
[2024-05-12T17:45:46.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:45:46.109+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:45:46.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:45:47.743+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:45:48.302+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:45:48.301+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:45:48.646+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:45:48.645+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:45:48.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.756 seconds
[2024-05-12T17:46:19.230+0000] {processor.py:153} INFO - Started process (PID=1561) to work on /opt/airflow/dags/main.py
[2024-05-12T17:46:19.233+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:46:19.236+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:46:19.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:46:20.005+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:46:20.115+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:46:20.109+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:46:20.244+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:46:20.243+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:46:20.322+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 1.110 seconds
[2024-05-12T17:46:50.714+0000] {processor.py:153} INFO - Started process (PID=1616) to work on /opt/airflow/dags/main.py
[2024-05-12T17:46:50.716+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:46:50.725+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:46:50.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:46:51.204+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:46:51.275+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:46:51.274+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:46:51.363+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:46:51.363+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:46:51.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 0.741 seconds
[2024-05-12T17:47:21.936+0000] {processor.py:153} INFO - Started process (PID=1680) to work on /opt/airflow/dags/main.py
[2024-05-12T17:47:21.954+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:47:21.957+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:47:21.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:47:23.553+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:47:23.759+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:47:23.757+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:47:23.904+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:47:23.903+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:47:24.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 2.215 seconds
[2024-05-12T17:48:21.420+0000] {processor.py:153} INFO - Started process (PID=1753) to work on /opt/airflow/dags/main.py
[2024-05-12T17:48:21.438+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:48:21.458+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:48:21.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:48:25.353+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:48:25.980+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:48:25.968+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:48:26.783+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:48:26.755+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:48:27.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 6.219 seconds
[2024-05-12T17:49:14.175+0000] {processor.py:153} INFO - Started process (PID=1797) to work on /opt/airflow/dags/main.py
[2024-05-12T17:49:14.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:49:14.293+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:49:14.293+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:49:20.825+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:49:21.538+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:49:21.536+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:49:22.133+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:49:22.133+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:49:22.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 8.837 seconds
[2024-05-12T17:50:52.668+0000] {processor.py:153} INFO - Started process (PID=1874) to work on /opt/airflow/dags/main.py
[2024-05-12T17:50:52.837+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/main.py for tasks to queue
[2024-05-12T17:50:52.886+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:50:52.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/main.py
[2024-05-12T17:51:01.508+0000] {processor.py:753} INFO - DAG(s) dict_keys(['mlops_A2_dag']) retrieved from /opt/airflow/dags/main.py
[2024-05-12T17:51:02.991+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:51:02.898+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2024-05-12T17:51:04.485+0000] {logging_mixin.py:137} INFO - [2024-05-12T17:51:04.485+0000] {dag.py:3441} INFO - Setting next_dagrun for mlops_A2_dag to 2024-05-12T17:27:34.109181+00:00, run_after=2024-05-13T17:27:34.109181+00:00
[2024-05-12T17:51:05.567+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/main.py took 13.025 seconds
